In [1]:
import pdb

In [44]:
import os

import numpy as np
import pandas as pd

def fn_getSamples(bPositive, strPart, strJobsDir):
    npNArrTotalSamples = []
    for name in os.listdir(strJobsDir):
        pdb.set_trace()
        strJobDir = os.path.join(strJobsDir, name)
        npNArrJobSamples = fn_getSamplesFromAJob(bPositive, strPart, strJobDir)
        for npNArr in npNArrJobSamples:
            npNArrTotalSamples.append(npNArr)
    
    npSamples = np.array(npNArrTotalSamples)
    return npSamples
        
        
def fn_getSamplesFromAJob(bPositive, strPart, strJobDir):
    npNArrSamples = []
    strSpecificDir = ""
    if bPositive:
        strSpecificDir = os.path.join(strJobDir, "samples/positive")
    else:
        strSpecificDir = os.path.join(strJobDir, "samples/negtive")
        
    for name in os.listdir(strSpecificDir):
        strStatusDir = os.path.join(strSpecificDir, name)
        strSectionsDir = os.path.join(strStatusDir, "sections")
        for name in os.listdir(strSectionsDir):
            if name == strPart:
                strSectionDir = os.path.join(strSectionsDir, name)
                npNArr = np.load(os.path.join(strSectionDir, "status.npy"))
                npNArrSamples.append(npNArr)
                break
                
    return npNArrSamples

In [46]:
fn_getSamples(False, "input", "jobs")

> <ipython-input-44-c47e951dc13d>(10)fn_getSamples()
-> strJobDir = os.path.join(strJobsDir, name)
(Pdb) list
  5  	
  6  	def fn_getSamples(bPositive, strPart, strJobsDir):
  7  	    npNArrTotalSamples = []
  8  	    for name in os.listdir(strJobsDir):
  9  	        pdb.set_trace()
 10  ->	        strJobDir = os.path.join(strJobsDir, name)
 11  	        npNArrJobSamples = fn_getSamplesFromAJob(bPositive, strPart, strJobDir)
 12  	        for npNArr in npNArrJobSamples:
 13  	            npNArrTotalSamples.append(npNArr)
 14  	
 15  	    npSamples = np.array(npNArrTotalSamples)
(Pdb) c
> <ipython-input-44-c47e951dc13d>(9)fn_getSamples()
-> pdb.set_trace()
(Pdb) npNArrTotalSamples
[array([[-42.1667 ,   0.67019,   0.     ],
       [-18.5198 ,  18.773  ,   0.     ],
       [-16.4406 ,  19.1835 ,   0.     ],
       [-13.896  ,  18.567  ,   0.     ],
       [-10.2475 ,  19.1894 ,   0.     ],
       [ -7.74753,  20.0617 ,   0.     ],
       [ -8.94555,  20.1179 ,   0.     ],
       [-12.6485

array([[[-42.1667 ,   0.67019,   0.     ],
        [-18.5198 ,  18.773  ,   0.     ],
        [-16.4406 ,  19.1835 ,   0.     ],
        [-13.896  ,  18.567  ,   0.     ],
        [-10.2475 ,  19.1894 ,   0.     ],
        [ -7.74753,  20.0617 ,   0.     ],
        [ -8.94555,  20.1179 ,   0.     ],
        [-12.6485 ,  19.0891 ,   0.     ],
        [-15.698  ,  18.5182 ,   0.     ],
        [-17.8267 ,  18.7716 ,   0.     ]],

       [[-33.75   ,   3.00932,   0.     ],
        [-17.6287 ,  19.4556 ,   0.     ],
        [-15.698  ,  20.2057 ,   0.     ],
        [-13.2573 ,  20.1782 ,   0.     ],
        [-10.8058 ,  20.2392 ,   0.     ],
        [ -8.86893,  20.1237 ,   0.     ],
        [ -9.85437,  20.6414 ,   0.     ],
        [-12.3058 ,  20.5603 ,   0.     ],
        [-15.1117 ,  20.5093 ,   0.     ],
        [-17.3317 ,  19.6978 ,   0.     ]],

       [[-42.703  ,   3.723  ,   0.     ],
        [-19.947  ,  20.178  ,   0.     ],
        [-18.398  ,  20.377  ,   0.     ],
       

In [38]:
npNArr = np.array([[2, 3, 4], [5, 8, 9]])
print(npNArr[:, 1:])

[[3 4]
 [8 9]]


In [31]:
npNArr1 = np.array(npNArr)

npNArr2 = np.array([npNArr, npNArr1])
npNArr2
for n in npNArr2:
    print(n)

[[2 3 4]
 [5 8 9]]
[[2 3 4]
 [5 8 9]]
